### ISSUE TITLE
Failure during "combining paired-end reads" step

### ISSUE THREAD

**Issue by daisieh** [V-Z/sondovac#1] opened 2015-08-29 04:52 UTC
I could not get the pipeline to run as expected. I executed the pipeline as `sondovac_part_a.sh -n -f sample_data/input1_JHCN_SOAPdenovo_TransAssembly_dnas.fa -c sample_data/input2_Ricinus_communis_reference.fsa -m sample_data/input5_Ricinus_communis_mitochondrion.fasta -t sample_data/input3_J120_S1_L001_R1_001.fastq -q sample_data/input4_J120_S1_L001_R2_001.fastq`. 

I got one error that I was able to work around, which was the sed line at 866: I had to remove the `-r` flag. 

I then got another error: 

```
Combining paired-end reads

[FLASH] ERROR: Failed to open "./sample_data/input1_JHCN_SOAPdenovo_TransAssembly_dnas_combined_reads_co_cp_no_mt_reads.extendedFrags.fastq" for writing: No such file or directory
[FLASH] FLASH did not complete successfully; exiting with failure status (1)

Error! Combining paired-end reads failed. Aborting. Check files 250, sample_data/input1_JHCN_SOAPdenovo_TransAssembly_dnas_genome_skim_data_no_cp_no_mt_reads_1.fq and sample_data/input1_JHCN_SOAPdenovo_TransAssembly_dnas_genome_skim_data_no_cp_no_mt_reads_2.fq.
```

**Comment by V-Z** [comment] 2015-08-31 15:24
Hello,
I'm sorry for late reply (_I edited the reply as I found my original answer was wrong_).
Regarding the `sed` on line 866, what was the error? The `-r` flag is supposed to explicitly use extended regular expressions. Which version of sed do You have? What is Your operating system (including version)?
Regarding the second error with names, this is our mistake. There was wrong `input1` file. I thought I have replaced those originally. I replaced [sample_data](https://github.com/V-Z/sondovac/releases/tag/sample-data) package. So that it should be correct now.
Sorry for troubles... Please, let me know if this works for You.

**Comment by V-Z** [comment] 2015-10-07 14:50
The issue is fixed in v. 0.7.

**Closed as completed by V-Z** 2015-10-07 14:50 UTC
Labels: bug
